server:
  port: 80

spring:
  application:
    name: cloud-order-service #服务名称

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/
      defaultZone: http://127.0.0.1:7001/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: order80
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 20
    ip-address: 127.0.0.1