server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: CLOUD-PAYMENT-SERVICE # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
              #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
              #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
              #- Cookie=username,zzyy
              #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
              #- Host=**.atguigu.com
              #- Method=GET
              #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
              # 过滤
            #filters:
            #  - AddRequestHeader=X-Request-red, blue

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/
      defaultZone: http://127.0.0.1:7001/eureka/
    instance:
      instance-id: gateway9527
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 2
      lease-expiration-duration-in-seconds: 20
      ip-address: 127.0.0.1
